apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: josh-crossplane-bucket-100-100
  labels:
    test: test
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default


